import { MenuTemplate } from '../types';

export const MENU_TEMPLATES: MenuTemplate[] = [
  {
    id: 'modern',
    name: 'Hiện đại Cam Nóng',
    description: 'Nhấn mạnh CTA và giá, phù hợp menu bán nhanh.',
    badge: 'Fast Sell',
    primaryColor: '#FF5800',
    secondaryColor: '#FFF6EF',
    fontFamily: 'Inter',
    sizePreset: 'normal',
    currency: 'VND',
    layout: 'stacked',
    cardStyle: 'soft',
    navStyle: 'pill',
    backgroundStyle: 'soft',
  },
  {
    id: 'classic',
    name: 'Cổ điển Thanh lịch',
    description: 'Phong cách trang nhã, hợp menu cao cấp.',
    badge: 'Elegant',
    primaryColor: '#2F2A38',
    secondaryColor: '#F3F0ED',
    fontFamily: 'Playfair Display',
    sizePreset: 'normal',
    currency: 'EUR',
    layout: 'editorial',
    cardStyle: 'outline',
    navStyle: 'underline',
    backgroundStyle: 'paper',
  },
  {
    id: 'minimal',
    name: 'Tối giản Bắc Âu',
    description: 'Sạch sẽ, dễ đọc, tập trung thông tin.',
    badge: 'Minimal',
    primaryColor: '#1D4ED8',
    secondaryColor: '#F4F8FF',
    fontFamily: 'Roboto',
    sizePreset: 'compact',
    currency: 'USD',
    layout: 'split',
    cardStyle: 'outline',
    navStyle: 'block',
    backgroundStyle: 'solid',
  },
  {
    id: 'bakery',
    name: 'Bakery Warm Editorial',
    description: 'Phong cách bakery ấm áp, ảnh lớn và modal chi tiết rõ ràng.',
    badge: 'Bakery',
    primaryColor: '#8F4F2D',
    secondaryColor: '#F6EBDD',
    fontFamily: 'Playfair Display',
    sizePreset: 'normal',
    currency: 'VND',
    layout: 'editorial',
    cardStyle: 'soft',
    navStyle: 'pill',
    backgroundStyle: 'paper',
  },
  {
    id: 'organic_market',
    name: 'Organic Market Panel',
    description: 'Phong cách organic góc cạnh, tách biệt Bakery với panel rõ khối và CTA mạnh.',
    badge: 'Organic',
    primaryColor: '#6A7F34',
    secondaryColor: '#EDF1DF',
    fontFamily: 'Be Vietnam Pro',
    sizePreset: 'normal',
    currency: 'VND',
    layout: 'stacked',
    cardStyle: 'soft',
    navStyle: 'pill',
    backgroundStyle: 'soft',
  },
  {
    id: 'coffee_atelier',
    name: 'Coffee Atelier Studio',
    description: 'Hero typography ấn tượng, tông cà phê cao cấp và modal chi tiết giàu nội dung.',
    badge: 'Atelier',
    primaryColor: '#A8683A',
    secondaryColor: '#F1EDE7',
    fontFamily: 'Playfair Display',
    sizePreset: 'normal',
    currency: 'VND',
    layout: 'editorial',
    cardStyle: 'soft',
    navStyle: 'pill',
    backgroundStyle: 'paper',
  },
  {
    id: 'vibrant',
    name: 'Vibrant Cam Sôi Động',
    description: 'Thiết kế sống động với cam cam, phù hợp fastfood và quán ăn nhanh.',
    badge: 'Vibrant',
    primaryColor: '#FF6B35',
    secondaryColor: '#FFF6EF',
    fontFamily: 'Inter',
    sizePreset: 'normal',
    currency: 'VND',
    layout: 'split',
    cardStyle: 'soft',
    navStyle: 'pill',
    backgroundStyle: 'soft',
  },
  {
    id: 'modern_grid',
    name: 'Modern Grid',
    description: 'Grid layout with promo cards and icon categories for a fresh mobile experience.',
    badge: 'Modern',
    primaryColor: '#0D9A6B',
    secondaryColor: '#EAFBF4',
    fontFamily: 'Roboto',
    sizePreset: 'normal',
    currency: 'VND',
    layout: 'split',
    cardStyle: 'soft',
    navStyle: 'pill',
    backgroundStyle: 'soft',
  },
  {
    id: 'vintage',
    name: 'Vintage Thủ công',
    description: 'Tông ấm nhẹ và chất liệu giấy cổ điển.',
    badge: 'Retro',
    primaryColor: '#9A5A35',
    secondaryColor: '#F8EFE4',
    fontFamily: 'Playfair Display',
    sizePreset: 'normal',
    currency: 'EUR',
    layout: 'stacked',
    cardStyle: 'solid',
    navStyle: 'pill',
    backgroundStyle: 'paper',
  },
  {
    id: 'eco',
    name: 'Eco Tự nhiên',
    description: 'Màu xanh dịu, phù hợp thực đơn organic.',
    badge: 'Organic',
    primaryColor: '#2F7D4A',
    secondaryColor: '#ECF8EF',
    fontFamily: 'Be Vietnam Pro',
    sizePreset: 'normal',
    currency: 'VND',
    layout: 'stacked',
    cardStyle: 'soft',
    navStyle: 'block',
    backgroundStyle: 'soft',
  },
  {
    id: 'luxury',
    name: 'Luxury Đen Vàng',
    description: 'Nhấn chất premium với nhịp điệu editorial.',
    badge: 'Premium',
    primaryColor: '#222222',
    secondaryColor: '#F8F2E7',
    fontFamily: 'Playfair Display',
    sizePreset: 'large',
    currency: 'USD',
    layout: 'editorial',
    cardStyle: 'solid',
    navStyle: 'underline',
    backgroundStyle: 'duotone',
  },
  {
    id: 'fresh',
    name: 'Fresh Sáng tạo',
    description: 'Trẻ trung, tương phản nhẹ, dễ dùng di động.',
    badge: 'Fresh',
    primaryColor: '#0D9A6B',
    secondaryColor: '#EAFBF4',
    fontFamily: 'Be Vietnam Pro',
    sizePreset: 'normal',
    currency: 'VND',
    layout: 'split',
    cardStyle: 'soft',
    navStyle: 'pill',
    backgroundStyle: 'soft',
  },
  {
    id: 'bold',
    name: 'Bold Năng lượng',
    description: 'Đậm, rõ, phù hợp menu combo và khuyến mãi.',
    badge: 'Bold',
    primaryColor: '#D93B16',
    secondaryColor: '#FFF1EB',
    fontFamily: 'Inter',
    sizePreset: 'large',
    currency: 'USD',
    layout: 'split',
    cardStyle: 'solid',
    navStyle: 'block',
    backgroundStyle: 'duotone',
  },
  {
    id: 'cozy',
    name: 'Cozy Ấm áp',
    description: 'Dịu mắt, thân thiện cho quán nhỏ.',
    badge: 'Warm',
    primaryColor: '#B24A3D',
    secondaryColor: '#FFF4EE',
    fontFamily: 'Be Vietnam Pro',
    sizePreset: 'normal',
    currency: 'VND',
    layout: 'stacked',
    cardStyle: 'soft',
    navStyle: 'pill',
    backgroundStyle: 'paper',
  },
  {
    id: 'tech',
    name: 'Tech Tương lai',
    description: 'Tinh gọn, sắc nét, hợp sản phẩm công nghệ.',
    badge: 'Tech',
    primaryColor: '#1F4073',
    secondaryColor: '#EAF2FF',
    fontFamily: 'Roboto',
    sizePreset: 'compact',
    currency: 'USD',
    layout: 'split',
    cardStyle: 'outline',
    navStyle: 'underline',
    backgroundStyle: 'solid',
  },
];

export const DEFAULT_MENU_TEMPLATE = MENU_TEMPLATES[0];

export function getMenuTemplateById(templateId?: string): MenuTemplate {
  return MENU_TEMPLATES.find((template) => template.id === templateId) || DEFAULT_MENU_TEMPLATE;
}